---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console 
summary: 'La NetApp Console doit avoir accès à l"API Google Cloud NetApp Volumes et aux autorisations appropriées via un compte de service Google Cloud.' 
---
= Configurer les Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console a besoin des autorisations appropriées via un compte de service Google Cloud.

Effectuez les tâches suivantes pour que la NetApp Console puisse accéder à votre projet Google Cloud.

* Si vous n’avez pas encore de compte de service existant, créez-en un nouveau.
* Accorder l'accès pour usurpation d'identité.
* Accordez le rôle IAM dans le projet partagé.




== Configurer un compte de service

. Dans la console Google Cloud, https://console.cloud.google.com/iam-admin/serviceaccounts["aller à la page Comptes de service"^] .
. Cliquez sur *Sélectionner un projet*, choisissez votre projet et cliquez sur *Ouvrir*.
. Pour créer un compte de service, procédez comme suit :
+
.. Cliquez sur *Créer un compte de service*.
.. Saisissez le nom du compte de service (nom d’affichage convivial) et la description.
+
La console Google Cloud génère un ID de compte de service basé sur ce nom.  Modifiez l'ID si nécessaire - vous ne pourrez pas modifier l'ID ultérieurement.

.. Cliquez sur *Créer et continuer*.
.. Dans la liste des rôles, sélectionnez le rôle * administrateur Google Cloud NetApp Volumes * ou * visionneuse Google Cloud NetApp *.
.. Sélectionnez *Continuer*.
.. Accordez un accès par usurpation d'identité à ce compte de service : credentials-sa@wf-production-netapp.iam.gserviceaccount.com. Pour plus de détails, voir https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["Créer un jeton Web JSON (JWT) auto-signé"^] .
+
Le compte de service appartenant à NetApp est utilisé pour demander un jeton d'accès temporaire qui vous permet d'agir en tant que ce compte de service sans avoir besoin d'accéder à sa clé privée.

.. Cliquez sur *TERMINÉ* en bas de la page, puis passez à l'étape suivante.






== VPC partagé

Dans chaque projet GCP supplémentaire qui utilisera le compte de service, procédez comme suit :

. Dans la page _IAM_, sélectionnez le projet hôte VPC partagé dans le menu déroulant du projet.
. Cliquez sur *Ajouter un principal*.
. Dans le champ Nouveaux principaux, saisissez l’adresse e-mail de votre compte de service.
. Dans la liste déroulante Sélectionner un rôle, choisissez le rôle * Administrateur Google Cloud NetApp Volumes *.
. Cliquez sur *Enregistrer*.


Pour connaître les étapes détaillées, reportez-vous à la documentation de Google Cloud :

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["Création et gestion des comptes de service"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Rôles et autorisations de Google Cloud NetApp Volumes"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["Accorder, modifier et révoquer l'accès aux ressources"^]




== Dépannage

Si vous rencontrez une erreur, la politique *iam.disableCrossProjectServiceAccountUsage* pourrait être appliquée.  Pour remédier à cela, procédez comme suit :

. Dans la console Google Cloud, accédez à https://console.cloud.google.com/iam-admin/orgpolicies["page sur les politiques de l'organisation"^] .
. Recherchez la stratégie *Désactiver l'utilisation des comptes de service inter-projets* et désactivez-la.


.Quelle est la prochaine étape ?
link:task-add-roles.html["Attribuer des rôles à Google Cloud NetApp Volumes"].
