---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Découvrez les nouveautés concernant la prise en charge de Google Cloud NetApp Volumes dans NetApp Console. 
---
= Quoi de neuf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés concernant la prise en charge de Google Cloud NetApp Volumes dans NetApp Console.



== 27 novembre 2025



=== Modifications des identifiants Google Cloud Platform

À mesure que les clients configurent et autorisent davantage de systèmes Google Cloud NetApp Volumes , la gestion des identifiants a évolué.

Les informations d'identification des systèmes NetApp Volumes sont désormais stockées sur un serveur cloud Google, tel que le service Cloud Key Management ou un service similaire, et les informations d'identification d'emprunt d'identité du compte de service sont utilisées lors de la création d'un nouveau système.



== 06 octobre 2025



=== BlueXP est désormais NetApp Console

La NetApp Console, construite sur la base BlueXP améliorée et restructurée, fournit une gestion centralisée du stockage NetApp et des NetApp Data Services dans les environnements sur site et cloud à l'échelle de l'entreprise, offrant des informations en temps réel, des flux de travail plus rapides et une administration simplifiée, hautement sécurisée et conforme.

Pour plus de détails sur ce qui a changé, consultez lelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notes de version de la NetApp Console"] .



== 21 juillet 2025



=== Prise en charge des Google Cloud NetApp Volumes dans BlueXP

Vous pouvez désormais gérer les Google Cloud NetApp Volumes directement depuis BlueXP:

* Ajoutez un environnement de travail.
* Voir les volumes.
* Supprimer les environnements de travail.

